name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - Dashtid

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module would this feature affect?
      options:
        - Threat Intelligence (Phase 1)
        - ML Risk Scoring (Phase 2)
        - Anomaly Detection (Phase 3)
        - Adversarial ML (Phase 4)
        - SBOM Analysis (Phase 5)
        - API/Dashboard
        - Federated Learning
        - Network Capture
        - DefectDojo Integration
        - New Module
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/Blocker
    validations:
      required: true

  - type: dropdown
    id: compliance
    attributes:
      label: Regulatory Relevance
      description: Is this related to regulatory compliance?
      options:
        - Not applicable
        - FDA Cybersecurity Guidance
        - EU MDR (2017/745)
        - IEC 62304
        - IEC 81001-5-1
        - HIPAA
        - Other

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature.
      placeholder: How would you use this feature in practice?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
        - label: I can provide test data or examples

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
